/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.DAO;
import Model.ChiTietHoaDon;
import Model.HoaDon;
import Model.NhanVien;
import Model.SanPham;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Nhom24
 */
public class BanHang extends javax.swing.JDialog implements View {

    /**
     * Creates new form BanHang
     */
    private DangNhap dn;
    private List<SanPham> listSP;
    private DefaultTableModel modelSP;
    private List<NhanVien> listNV;
    private DefaultTableModel modelNV;
    private List<SanPham> listSP1;
    private DefaultTableModel modelSP1;
    private List<ChiTietHoaDon> listNhapXuat; 
    private DefaultTableModel modelNhapXuat;
    private List<SanPham> listSP2;
    private DefaultTableModel modelSP2;
    private List<ChiTietHoaDon> listBanHang; 
    private DefaultTableModel modelBanHang;
    private List<HoaDon> listHD;

    public BanHang(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        dn = (DangNhap) parent;
        lbNhanvien.setText(dn.getNhanvien());
        listSP2 = new DAO().getListSanPham("SELECT * FROM tblsanpham");
        modelSP2 = (DefaultTableModel) tblSanPham2.getModel();
        listBanHang = new ArrayList<>();
        modelBanHang = (DefaultTableModel) tblBanHang.getModel();

        showData(listSP2, modelSP2);

    }

    public String xulyngay(String date) {
        String[] arrdate = date.split("-");
        String ngay = arrdate[2] + "/" + arrdate[1] + "/" + arrdate[0];
        return ngay;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lbNhanvien = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        tfMaSP2 = new javax.swing.JTextField();
        tfTenSP2 = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        tfGiaNhap2 = new javax.swing.JTextField();
        tfGiaBan2 = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        tfNHH2 = new javax.swing.JTextField();
        timKiemSP2 = new javax.swing.JButton();
        LamMoiSP2 = new javax.swing.JButton();
        capnhatSP2 = new javax.swing.JButton();
        cbNhomSP2 = new javax.swing.JComboBox<>();
        tfNSX2 = new javax.swing.JTextField();
        jScrollPane6 = new javax.swing.JScrollPane();
        tblSanPham2 = new javax.swing.JTable();
        jLabel36 = new javax.swing.JLabel();
        nhapMaSP2 = new javax.swing.JButton();
        tfNhapSoLuong2 = new javax.swing.JTextField();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblBanHang = new javax.swing.JTable();
        xoaPhieu2 = new javax.swing.JButton();
        taoMoiHD2 = new javax.swing.JButton();
        luuPhieu2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        lbTongTien2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Anh/icon thu ngân.png"))); // NOI18N
        jLabel1.setText("     Nhân Viên Bán Hàng");
        jLabel1.setVerifyInputWhenFocusTarget(false);

        lbNhanvien.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lbNhanvien.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbNhanvien.setText("jLabel3");

        jLabel4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Anh/icon nhânvien.png"))); // NOI18N
        jLabel4.setText("  Nhân Viên: ");

        jButton1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Anh/icon đăng xuất.png"))); // NOI18N
        jButton1.setText("Đăng Xuất");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel6.setBackground(new java.awt.Color(153, 204, 255));

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel28.setText("Mã SP");

        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel29.setText("Tên SP");

        jLabel30.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel30.setText("Hãng SX");

        jLabel31.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel31.setText("Giá Nhập");

        jLabel32.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel32.setText("Giá Bán");

        jLabel33.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel33.setText("Ngày Sản Xuất");

        jLabel34.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel34.setText("Ngày Nhập Hàng");

        timKiemSP2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        timKiemSP2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Anh/icon tìm kiếm.png"))); // NOI18N
        timKiemSP2.setText("Tìm Kiếm");
        timKiemSP2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timKiemSP2ActionPerformed(evt);
            }
        });

        LamMoiSP2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        LamMoiSP2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Anh/icon refresh.png"))); // NOI18N
        LamMoiSP2.setText("Làm Mới");
        LamMoiSP2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LamMoiSP2ActionPerformed(evt);
            }
        });

        capnhatSP2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        capnhatSP2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Anh/icon cập nhật.png"))); // NOI18N
        capnhatSP2.setText("Cập Nhật");
        capnhatSP2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                capnhatSP2ActionPerformed(evt);
            }
        });

        cbNhomSP2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cbNhomSP2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "IPhone", "SamSung" }));

        tfNSX2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNSX2ActionPerformed(evt);
            }
        });

        tblSanPham2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Mã Sản Phẩm", "Tên Sản Phẩm", "Nhóm Sản Phẩm", "Số Lượng"
            }
        ));
        tblSanPham2.setAutoscrolls(false);
        tblSanPham2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tblSanPham2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSanPham2MouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(tblSanPham2);

        jLabel36.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel36.setText("Tạo Hóa Đơn");

        nhapMaSP2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        nhapMaSP2.setText("Nhập Mã Sản Phẩm");
        nhapMaSP2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nhapMaSP2ActionPerformed(evt);
            }
        });

        tblBanHang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Mã Sản Phẩm", "Tên Sản Phẩm", "Thành Tiền"
            }
        ));
        tblBanHang.setAutoscrolls(false);
        tblBanHang.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tblBanHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblBanHangMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(tblBanHang);

        xoaPhieu2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        xoaPhieu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Anh/icon xóa.png"))); // NOI18N
        xoaPhieu2.setText("  Xoá");
        xoaPhieu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xoaPhieu2ActionPerformed(evt);
            }
        });

        taoMoiHD2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        taoMoiHD2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Anh/icon refresh.png"))); // NOI18N
        taoMoiHD2.setText("  Hóa Đơn Mới");
        taoMoiHD2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                taoMoiHD2ActionPerformed(evt);
            }
        });

        luuPhieu2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        luuPhieu2.setText("Lưu Phiếu");
        luuPhieu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                luuPhieu2ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Anh/icon xiền.png"))); // NOI18N
        jLabel2.setText("Tổng Tiền");

        lbTongTien2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbTongTien2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTongTien2.setText("0.0");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(57, 57, 57)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(tfMaSP2, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(tfTenSP2, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(174, 174, 174)
                                .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(cbNhomSP2, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfGiaNhap2, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfGiaBan2, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel33, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel34, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(37, 37, 37)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfNHH2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfNSX2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(timKiemSP2, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(LamMoiSP2, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(capnhatSP2, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tfNhapSoLuong2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(65, 65, 65)
                                .addComponent(nhapMaSP2, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(105, 105, 105))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(xoaPhieu2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(68, 68, 68)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel36)
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addComponent(taoMoiHD2)
                                        .addGap(62, 62, 62)
                                        .addComponent(luuPhieu2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addGap(55, 55, 55))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 626, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(lbTongTien2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(189, 189, 189))))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfNSX2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tfMaSP2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tfGiaNhap2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfNHH2, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel32)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jLabel34, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tfGiaBan2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(tfTenSP2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(11, 11, 11)))
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbNhomSP2, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                            .addComponent(jLabel30, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(86, 86, 86)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(timKiemSP2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LamMoiSP2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(capnhatSP2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jLabel36)
                        .addGap(39, 39, 39)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfNhapSoLuong2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(nhapMaSP2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE))
                        .addGap(33, 33, 33)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                            .addComponent(taoMoiHD2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(luuPhieu2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(xoaPhieu2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(35, 35, 35)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(lbTongTien2)))
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbNhanvien, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(85, 85, 85)
                .addComponent(jButton1)
                .addGap(60, 60, 60))
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jButton1))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbNhanvien, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabel1.getAccessibleContext().setAccessibleName("Nhân Viên Bán Hàng");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void timKiemSP2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timKiemSP2ActionPerformed
        if (tfMaSP2.getText().length() != 0) {
            String sql = "SELECT * FROM tblsanpham WHERE maSP LIKE '%" + tfMaSP2.getText() + "%'";
            listSP2 = new DAO().getListSanPham(sql);
            showData(listSP2, modelSP2);
        } else if (tfTenSP2.getText().length() != 0) {
            String sql = "SELECT * FROM tblsanpham WHERE tenSP LIKE '%" + tfTenSP2.getText() + "%'";
            listSP2 = new DAO().getListSanPham(sql);
            showData(listSP2, modelSP2);
        } else if (tfGiaNhap2.getText().length() != 0) {
            String sql = "SELECT * FROM tblsanpham WHERE gianhap LIKE '%" + tfGiaNhap2.getText() + "%'";
            listSP2 = new DAO().getListSanPham(sql);
            showData(listSP1, modelSP2);
        } else if (tfGiaBan2.getText().length() != 0) {
            String sql = "SELECT * FROM tblsanpham WHERE giaban LIKE '%" + tfGiaBan2.getText() + "%'";
            listSP2 = new DAO().getListSanPham(sql);
            showData(listSP2, modelSP2);
        } else if (tfNSX2.getText().length() != 0) {
            String sql = "SELECT * FROM tblsanpham WHERE ngaySX LIKE '%" + tfNSX2.getText() + "%'";
            listSP2 = new DAO().getListSanPham(sql);
            showData(listSP2, modelSP2);
        } else if (tfNHH2.getText().length() != 0) {
            String sql = "SELECT * FROM tblsanpham WHERE hanSD LIKE '%" + tfNHH2.getText() + "%'";
            listSP2 = new DAO().getListSanPham(sql);
            showData(listSP2, modelSP2);
        } else {
            String sql = "SELECT * FROM tblsanpham WHERE nhomSP LIKE '%" + cbNhomSP2.getSelectedItem().toString() + "%'";
            listSP2 = new DAO().getListSanPham(sql);
            showData(listSP2, modelSP2);
        }
    }//GEN-LAST:event_timKiemSP2ActionPerformed

    private void LamMoiSP2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LamMoiSP2ActionPerformed
        tfMaSP2.setText("");
        tfTenSP2.setText("");
        tfGiaNhap2.setText("");
        tfGiaBan2.setText("");
        tfNSX2.setText("");
        tfNHH2.setText("");
    }//GEN-LAST:event_LamMoiSP2ActionPerformed

    private void capnhatSP2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_capnhatSP2ActionPerformed
        String sql = "SELECT * FROM tblsanpham";
        listSP2 = new DAO().getListSanPham(sql);
        showData(listSP2, modelSP2);
    }//GEN-LAST:event_capnhatSP2ActionPerformed

    private void tblSanPham2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSanPham2MouseClicked
        int selectRow = tblSanPham2.getSelectedRow();
        hienthiSP(selectRow, "tabbanhang1");
    }//GEN-LAST:event_tblSanPham2MouseClicked

    private void nhapMaSP2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nhapMaSP2ActionPerformed
        float tongtien = Float.parseFloat(lbTongTien2.getText());
        String masp = tfNhapSoLuong2.getText();
        int slsql = 0;
        String sql = "SELECT * FROM tblsanpham WHERE maSP = " + tfMaSP2.getText();
        listSP = new DAO().getListSanPham(sql);
        for (SanPham sp : listSP) {
            slsql = sp.getMaSP();
        }
        if (masp.length() == 0) {
            JOptionPane.showMessageDialog(rootPane, "Số lượng không được để trống");
        } else if (!tfNhapSoLuong2.getText().matches("\\d+")) {
            JOptionPane.showMessageDialog(rootPane, "Số lượng phải là số");
        } else if (slsql < Integer.parseInt(masp)) {
            JOptionPane.showMessageDialog(rootPane, "Số lượng trong kho không đủ để xuất");
        } else if (slsql >= Integer.parseInt(masp)) {
            for (SanPham sp : listSP) {
                ChiTietHoaDon cthd = new ChiTietHoaDon();
                cthd.setMaSP(sp.getMaSP());
                cthd.setTenSP(sp.getTenSP());
                cthd.setThanhtien(sp.getGiaBan());

                tongtien += cthd.getThanhtien();
                lbTongTien2.setText(String.valueOf(tongtien));
                listBanHang.add(cthd);
                showData(listBanHang, modelBanHang);
            }
        }
        tfNhapSoLuong2.setText("");
    }//GEN-LAST:event_nhapMaSP2ActionPerformed

    private void tblBanHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblBanHangMouseClicked
        int selectRow = tblBanHang.getSelectedRow();
        hienthiSP(selectRow, "tabbanhang2");
    }//GEN-LAST:event_tblBanHangMouseClicked

    private void xoaPhieu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xoaPhieu2ActionPerformed
        listBanHang.remove(tblBanHang.getSelectedRow());
        showData(listBanHang, modelBanHang);
    }//GEN-LAST:event_xoaPhieu2ActionPerformed

    private void taoMoiHD2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_taoMoiHD2ActionPerformed
        listBanHang = new ArrayList<>();
        showData(listBanHang, modelBanHang);
        lbTongTien2.setText("0.0");
    }//GEN-LAST:event_taoMoiHD2ActionPerformed

    private void luuPhieu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_luuPhieu2ActionPerformed
        if (listBanHang.isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Hóa đơn đang trống bạn cần thêm sản phẩm !!!");
        } else {
            HoaDon hd = new HoaDon();
            String mahdcuoi = new DAO().getObject("SELECT MAX(maHD) FROM tblhoadon").toString();
            hd.setMaHD(Integer.parseInt(mahdcuoi) + 1);
            hd.setNgaytaoHD(new java.sql.Date(System.currentTimeMillis()));

            float tongtien = 0;
            int maCTHD = 1;
            for (ChiTietHoaDon cthd : listBanHang) {
                int slsql = 0;
                float giaban = 0;

                int msp = cthd.getMaSP();
                String sql = "SELECT * FROM tblsanpham WHERE maSP = " + msp;
                listSP = new DAO().getListSanPham(sql);
                for (SanPham sp : listSP) {
                    slsql = sp.getMaSP();
                    giaban = sp.getGiaBan();
                }
                cthd.setMaCTHD(maCTHD);
                cthd.setMaHD(hd.getMaHD());
                new DAO().themchitiethoaDon(cthd, "INSERT INTO tblchitiethoadon(machitietHD, maHD, maSP, tenSP, thanhtien) VALUES(?,?,?,?,?)");

                tongtien += giaban;
                maCTHD++;
            }

            hd.setTongtien(tongtien);

            if (new DAO().themhoaDon(hd, "INSERT INTO tblhoadon(maHD, ngaytao, tongtien) VALUES(?,?,?)")) {
                JOptionPane.showMessageDialog(rootPane, "Đã lưu hóa đơn");
            } else {
                JOptionPane.showMessageDialog(rootPane, "Thất bại");
            }
        }
    }//GEN-LAST:event_luuPhieu2ActionPerformed

    private void tfNSX2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNSX2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNSX2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BanHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BanHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BanHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BanHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                BanHang dialog = new BanHang(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LamMoiSP2;
    private javax.swing.JButton capnhatSP2;
    private javax.swing.JComboBox<String> cbNhomSP2;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JLabel lbNhanvien;
    private javax.swing.JLabel lbTongTien2;
    private javax.swing.JButton luuPhieu2;
    private javax.swing.JButton nhapMaSP2;
    private javax.swing.JButton taoMoiHD2;
    private javax.swing.JTable tblBanHang;
    private javax.swing.JTable tblSanPham2;
    private javax.swing.JTextField tfGiaBan2;
    private javax.swing.JTextField tfGiaNhap2;
    private javax.swing.JTextField tfMaSP2;
    private javax.swing.JTextField tfNHH2;
    private javax.swing.JTextField tfNSX2;
    private javax.swing.JTextField tfNhapSoLuong2;
    private javax.swing.JTextField tfTenSP2;
    private javax.swing.JButton timKiemSP2;
    private javax.swing.JButton xoaPhieu2;
    // End of variables declaration//GEN-END:variables

    @Override
    public <T> void showData(List<T> list, DefaultTableModel model) {
        model.setRowCount(0);
        int stt = 1;
        if (modelSP == model) {
            for (T t : list) {
                SanPham sp = (SanPham) t;
                model.addRow(new Object[]{
                    stt, sp.getMaSP(), sp.getTenSP(), sp.getNhomSP(), sp.getGiaNhap(), sp.getGiaBan(),
                    sp.getNgaySX(), sp.getHanSD()
                });
                stt++;
            }
        }
        if (modelSP1 == model) {
            for (T t : list) {
                SanPham sp = (SanPham) t;
                model.addRow(new Object[]{
                    stt, sp.getMaSP(), sp.getTenSP(), sp.getNhomSP()
                });
                stt++;
            }
        }
        if (modelNV == model) {
            for (T t : list) {
                NhanVien nv = (NhanVien) t;
                model.addRow(new Object[]{
                    stt, nv.getIdNv(), nv.getHoten(), nv.getDiachi(), nv.getNgaysinh(), nv.getSdt(),
                    nv.getTaikhoan(), nv.getMatkhau(), nv.getVitri()
                });
                stt++;
            }
        }
        if (modelSP2 == model) {
            for (T t : list) {
                SanPham sp = (SanPham) t;
                model.addRow(new Object[]{
                    stt, sp.getMaSP(), sp.getTenSP(), sp.getNhomSP()
                });
                stt++;
            }
        }
        if (modelNhapXuat == model) {
            for (T t : list) {
                ChiTietHoaDon cthd = (ChiTietHoaDon) t;
                model.addRow(new Object[]{
                    stt, cthd.getMaSP(), cthd.getTenSP(), cthd.getThanhtien()
                });
                stt++;
            }
        }
        if (modelBanHang == model) {
            for (T t : list) {
                ChiTietHoaDon cthd = (ChiTietHoaDon) t;
                model.addRow(new Object[]{
                    stt, cthd.getMaSP(), cthd.getTenSP(), cthd.getThanhtien()
                });
                stt++;
            }
        }
    }

    private void hienthiSP(int selectRow, String kt) {
        SanPham sp = new SanPham();
        ChiTietHoaDon cthd = new ChiTietHoaDon();
        if ("tabbanhang1".equals(kt)) {
            sp = listSP2.get(selectRow);

            String str1 = String.valueOf(sp.getNgaySX());
            String nsx = xulyngay(str1);
            String str2 = String.valueOf(sp.getHanSD());
            String hsd = xulyngay(str2);
            String str3 = String.valueOf(sp.getGiaNhap()).replace(".0", "");
            String str4 = String.valueOf(sp.getGiaBan()).replace(".0", "");

            tfMaSP2.setText(String.valueOf(sp.getMaSP()));
            tfTenSP2.setText(sp.getTenSP());
            cbNhomSP2.setSelectedItem(String.valueOf(sp.getNhomSP()));
            tfGiaNhap2.setText(str3);
            tfGiaBan2.setText(str4);
            tfNSX2.setText(nsx);
            tfNHH2.setText(hsd);

        } else if ("tabbanhang2".equals(kt)) {
            cthd = listBanHang.get(selectRow);
            String sql = "SELECT * FROM tblsanpham WHERE maSP = " + cthd.getMaSP();
            listSP = new DAO().getListSanPham(sql);
            sp = listSP.get(0);

            String str1 = String.valueOf(sp.getNgaySX());
            String nsx = xulyngay(str1);
            String str2 = String.valueOf(sp.getHanSD());
            String hsd = xulyngay(str2);
            String str3 = String.valueOf(sp.getGiaNhap()).replace(".0", "");
            String str4 = String.valueOf(sp.getGiaBan()).replace(".0", "");

            tfMaSP2.setText(String.valueOf(sp.getMaSP()));
            tfTenSP2.setText(sp.getTenSP());
            cbNhomSP2.setSelectedItem(String.valueOf(sp.getNhomSP()));
            tfGiaNhap2.setText(str3);
            tfGiaBan2.setText(str4);
            tfNSX2.setText(nsx);
            tfNHH2.setText(hsd);
        }

    }
}
