/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.DAO;
import Model.ChiTietHoaDon;
import Model.HoaDon;
import Model.NhanVien;
import Model.SanPham;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Nhom24
 */
public class KhoHang extends javax.swing.JDialog implements View {

    private DangNhap dn;
    private List<SanPham> listSP;
    private DefaultTableModel modelSP;
    private List<NhanVien> listNV;
    private DefaultTableModel modelNV;
    private List<SanPham> listSP1;
    private DefaultTableModel modelSP1;
    private List<ChiTietHoaDon> listNhapXuat; 
    private DefaultTableModel modelNhapXuat;
    private List<SanPham> listSP2;
    private DefaultTableModel modelSP2;
    private List<ChiTietHoaDon> listBanHang; 
    private DefaultTableModel modelBanHang;
    private List<HoaDon> listHD;

    public KhoHang(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        dn = (DangNhap) parent;
        lbnhanvien.setText(dn.getNhanvien());

        listSP1 = new DAO().getListSanPham("SELECT * FROM tblsanpham");
        modelSP1 = (DefaultTableModel) tblSanPham1.getModel();
        listNhapXuat = new ArrayList<>();
        modelNhapXuat = (DefaultTableModel) tblNhapXuat.getModel();

        showData(listSP1, modelSP1);
    }

    public String xulyngay(String date) {
        String[] arrdate = date.split("-");
        String ngay = arrdate[2] + "/" + arrdate[1] + "/" + arrdate[0];
        return ngay;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lbnhanvien = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        tfMaSP1 = new javax.swing.JTextField();
        tfTenSP1 = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        tfGiaNhap1 = new javax.swing.JTextField();
        tfGiaBan1 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblSanPham1 = new javax.swing.JTable();
        tfNHH1 = new javax.swing.JTextField();
        timKiemSP1 = new javax.swing.JButton();
        LamMoiSP1 = new javax.swing.JButton();
        capnhatSP1 = new javax.swing.JButton();
        cbNhomSP1 = new javax.swing.JComboBox<>();
        tfNSX1 = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblNhapXuat = new javax.swing.JTable();
        tfNhapSoLuong1 = new javax.swing.JTextField();
        nhapMaSP1 = new javax.swing.JButton();
        rdNhapHang = new javax.swing.JRadioButton();
        rdXuatHang = new javax.swing.JRadioButton();
        luuPhieu1 = new javax.swing.JButton();
        xoaPhieu1 = new javax.swing.JButton();
        taoMoiHD1 = new javax.swing.JButton();
        jLabel43 = new javax.swing.JLabel();
        lbTongTien1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Anh/icon kho.png"))); // NOI18N
        jLabel1.setText("  Nhân Viên Kho Hàng");
        jLabel1.setVerifyInputWhenFocusTarget(false);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Anh/icon nhânvien.png"))); // NOI18N
        jLabel3.setText("  Nhân Viên:");

        lbnhanvien.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lbnhanvien.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbnhanvien.setText("jLabel4");

        jButton1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Anh/icon đăng xuất.png"))); // NOI18N
        jButton1.setText("Đăng Xuất");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel5.setBackground(new java.awt.Color(153, 204, 255));
        jPanel5.setPreferredSize(new java.awt.Dimension(1171, 780));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel19.setText("Mã SP");

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel20.setText("Tên SP");

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel21.setText("Hãng SX");

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel22.setText("Giá Nhập");

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel23.setText("Giá Bán");

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel24.setText("Ngày Sản Xuất");

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel25.setText("Ngày Nhập Hàng");

        tblSanPham1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Mã Sản Phẩm", "Tên Sản Phẩm", "Nhóm Sản Phẩm"
            }
        ));
        tblSanPham1.setAutoscrolls(false);
        tblSanPham1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tblSanPham1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSanPham1MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblSanPham1);

        timKiemSP1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        timKiemSP1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Anh/icon tìm kiếm.png"))); // NOI18N
        timKiemSP1.setText("Tìm Kiếm");
        timKiemSP1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timKiemSP1ActionPerformed(evt);
            }
        });

        LamMoiSP1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        LamMoiSP1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Anh/icon refresh.png"))); // NOI18N
        LamMoiSP1.setText("Làm Mới");
        LamMoiSP1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LamMoiSP1ActionPerformed(evt);
            }
        });

        capnhatSP1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        capnhatSP1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Anh/icon cập nhật.png"))); // NOI18N
        capnhatSP1.setText("Cập Nhật");
        capnhatSP1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                capnhatSP1ActionPerformed(evt);
            }
        });

        cbNhomSP1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cbNhomSP1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "IPhone", "SamSung" }));

        jLabel26.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel26.setText("Nhập Hàng - Xuất Hàng");

        tblNhapXuat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Mã Sản Phẩm", "Tên Sản Phẩm", "Thành Tiền"
            }
        ));
        tblNhapXuat.setAutoscrolls(false);
        tblNhapXuat.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tblNhapXuat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblNhapXuatMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tblNhapXuat);

        nhapMaSP1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        nhapMaSP1.setText("Nhập Mã Sản Phẩm");
        nhapMaSP1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nhapMaSP1ActionPerformed(evt);
            }
        });

        rdNhapHang.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rdNhapHang.setText("Nhập Hàng");

        rdXuatHang.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rdXuatHang.setText("Xuất Hàng");

        luuPhieu1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        luuPhieu1.setText("Lưu Phiếu");
        luuPhieu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                luuPhieu1ActionPerformed(evt);
            }
        });

        xoaPhieu1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        xoaPhieu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Anh/icon xóa.png"))); // NOI18N
        xoaPhieu1.setText("  Xóa");
        xoaPhieu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xoaPhieu1ActionPerformed(evt);
            }
        });

        taoMoiHD1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        taoMoiHD1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Anh/icon refresh.png"))); // NOI18N
        taoMoiHD1.setText("  Hóa Đơn Mới");
        taoMoiHD1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                taoMoiHD1ActionPerformed(evt);
            }
        });

        jLabel43.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel43.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Anh/icon xiền.png"))); // NOI18N
        jLabel43.setText("Tổng Tiền");

        lbTongTien1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbTongTien1.setText("0.0");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 580, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(277, 277, 277)
                        .addComponent(jLabel43)
                        .addGap(18, 18, 18)
                        .addComponent(lbTongTien1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 640, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(xoaPhieu1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfGiaBan1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(254, 254, 254))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(tfGiaNhap1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 520, Short.MAX_VALUE))))))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(28, 28, 28)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(tfMaSP1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cbNhomSP1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tfTenSP1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(timKiemSP1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(LamMoiSP1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(164, 164, 164)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(capnhatSP1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel24)
                                .addGap(43, 43, 43)
                                .addComponent(tfNSX1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel25)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tfNHH1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(101, 101, 101))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(rdNhapHang)
                                .addGap(26, 26, 26)
                                .addComponent(rdXuatHang)
                                .addGap(47, 47, 47)
                                .addComponent(tfNhapSoLuong1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(taoMoiHD1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(luuPhieu1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(nhapMaSP1)))
                        .addGap(55, 55, 55))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfNSX1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel24)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(tfMaSP1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(tfGiaNhap1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(1, 1, 1)))
                .addGap(20, 20, 20)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(tfTenSP1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfNHH1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25)
                    .addComponent(tfGiaBan1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbNhomSP1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(61, 61, 61))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel26)
                        .addGap(33, 33, 33)))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(luuPhieu1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(taoMoiHD1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(xoaPhieu1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(57, 57, 57))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(timKiemSP1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(LamMoiSP1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(capnhatSP1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(rdNhapHang)
                                .addComponent(rdXuatHang)
                                .addComponent(tfNhapSoLuong1, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                                .addComponent(nhapMaSP1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel43, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbTongTien1))))
                .addGap(26, 26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 117, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbnhanvien, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(86, 86, 86)
                .addComponent(jButton1)
                .addGap(48, 48, 48))
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 1300, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(lbnhanvien, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1))))
                .addGap(18, 18, 18)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 809, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblSanPham1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSanPham1MouseClicked
        int selectRow = tblSanPham1.getSelectedRow();
        hienthiSP(selectRow, "tabqlkho1");
    }//GEN-LAST:event_tblSanPham1MouseClicked

    private void timKiemSP1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timKiemSP1ActionPerformed
        if (tfMaSP1.getText().length() != 0) {
            String sql = "SELECT * FROM tblsanpham WHERE maSP LIKE '%" + tfMaSP1.getText() + "%'";
            listSP1 = new DAO().getListSanPham(sql);
            showData(listSP1, modelSP1);
        } else if (tfTenSP1.getText().length() != 0) {
            String sql = "SELECT * FROM tblsanpham WHERE tenSP LIKE '%" + tfTenSP1.getText() + "%'";
            listSP1 = new DAO().getListSanPham(sql);
            showData(listSP1, modelSP1);
        } else if (tfGiaNhap1.getText().length() != 0) {
            String sql = "SELECT * FROM tblsanpham WHERE gianhap LIKE '%" + tfGiaNhap1.getText() + "%'";
            listSP1 = new DAO().getListSanPham(sql);
            showData(listSP1, modelSP1);
        } else if (tfGiaBan1.getText().length() != 0) {
            String sql = "SELECT * FROM tblsanpham WHERE giaban LIKE '%" + tfGiaBan1.getText() + "%'";
            listSP1 = new DAO().getListSanPham(sql);
            showData(listSP1, modelSP1);
        } else if (tfNSX1.getText().length() != 0) {
            String sql = "SELECT * FROM tblsanpham WHERE ngaySX LIKE '%" + tfNSX1.getText() + "%'";
            listSP1 = new DAO().getListSanPham(sql);
            showData(listSP1, modelSP1);
        } else if (tfNHH1.getText().length() != 0) {
            String sql = "SELECT * FROM tblsanpham WHERE hanSD LIKE '%" + tfNHH1.getText() + "%'";
            listSP1 = new DAO().getListSanPham(sql);
            showData(listSP1, modelSP1);
        } else {
            String sql = "SELECT * FROM tblsanpham WHERE nhomSP LIKE '%" + cbNhomSP1.getSelectedItem().toString() + "%'";
            listSP1 = new DAO().getListSanPham(sql);
            showData(listSP1, modelSP1);
        }
    }//GEN-LAST:event_timKiemSP1ActionPerformed

    private void LamMoiSP1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LamMoiSP1ActionPerformed
        tfMaSP1.setText("");
        tfTenSP1.setText("");
        tfGiaNhap1.setText("");
        tfGiaBan1.setText("");
        tfNSX1.setText("");
        tfNHH1.setText("");
    }//GEN-LAST:event_LamMoiSP1ActionPerformed

    private void capnhatSP1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_capnhatSP1ActionPerformed
        String sql = "SELECT * FROM tblsanpham";
        listSP1 = new DAO().getListSanPham(sql);
        showData(listSP1, modelSP1);
    }//GEN-LAST:event_capnhatSP1ActionPerformed

    private void tblNhapXuatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblNhapXuatMouseClicked
        int selectRow = tblNhapXuat.getSelectedRow();

        hienthiSP(selectRow, "tabqlkho2");
    }//GEN-LAST:event_tblNhapXuatMouseClicked

    private void nhapMaSP1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nhapMaSP1ActionPerformed
        if (rdXuatHang.isSelected()) {
            float tongtien = Float.parseFloat(lbTongTien1.getText());
            String masp = tfNhapSoLuong1.getText();
            int slsql = 0;
            String sql = "SELECT * FROM tblsanpham WHERE maSP = " + tfMaSP1.getText();
            listSP = new DAO().getListSanPham(sql);
            for (SanPham sp : listSP) {
                slsql = sp.getMaSP();
            }
            if (masp.length() == 0) {
                JOptionPane.showMessageDialog(rootPane, "Số lượng không được để trống");
            } else if (!tfNhapSoLuong1.getText().matches("\\d+")) {
                JOptionPane.showMessageDialog(rootPane, "Số lượng phải là số");
            } else if (slsql < Integer.parseInt(masp)) {
                JOptionPane.showMessageDialog(rootPane, "Số lượng trong kho không đủ để xuất");
            } else if (slsql >= Integer.parseInt(masp)) {
                for (SanPham sp : listSP) {
                    ChiTietHoaDon cthd = new ChiTietHoaDon();
                    cthd.setMaSP(sp.getMaSP());
                    cthd.setTenSP(sp.getTenSP());
                    cthd.setThanhtien(sp.getGiaNhap());

                    tongtien += cthd.getThanhtien();
                    lbTongTien1.setText(String.valueOf(tongtien));
                    listNhapXuat.add(cthd);
                    showData(listNhapXuat, modelNhapXuat);
                }
            }
            tfNhapSoLuong1.setText("");
        } 
        else if (rdNhapHang.isSelected()) {
            float tongtien = Float.parseFloat(lbTongTien1.getText());
            String masp = tfNhapSoLuong1.getText();
            String sql = "SELECT * FROM tblsanpham WHERE maSP = " + tfMaSP1.getText();
            listSP = new DAO().getListSanPham(sql);
            if (masp.length() == 0) {
                JOptionPane.showMessageDialog(rootPane, "Số lượng không được để trống");
            } else if (!tfNhapSoLuong1.getText().matches("\\d+")) {
                JOptionPane.showMessageDialog(rootPane, "Số lượng phải là số");
            } else {
                for (SanPham sp : listSP) {
                    ChiTietHoaDon cthd = new ChiTietHoaDon();
                    cthd.setMaSP(sp.getMaSP());
                    cthd.setTenSP(sp.getTenSP());
                    cthd.setThanhtien(sp.getGiaNhap());

                    tongtien += cthd.getThanhtien();
                    lbTongTien1.setText(String.valueOf(tongtien));
                    listNhapXuat.add(cthd);
                    showData(listNhapXuat, modelNhapXuat);
                }
            }
            tfNhapSoLuong1.setText("");
        } else {
            JOptionPane.showMessageDialog(rootPane, "Bạn phải chọn loại hóa đơn trước khi nhập số lượng");
        }
    }//GEN-LAST:event_nhapMaSP1ActionPerformed

    private void luuPhieu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_luuPhieu1ActionPerformed
        if (rdNhapHang.isSelected()) {
            HoaDon hd = new HoaDon();
            String mahdcuoi = new DAO().getObject("SELECT MAX(maHD) FROM tblnhaphang").toString();
            hd.setMaHD(Integer.parseInt(mahdcuoi) + 1);
            hd.setNgaytaoHD(new java.sql.Date(System.currentTimeMillis()));

            float tongtien = 0;
            int maCTHD = 1;
            for (ChiTietHoaDon cthd : listNhapXuat) {
                int slsql = 0;
                float gianhap = 0;

                int msp = cthd.getMaSP();
                String sql = "SELECT * FROM tblsanpham WHERE maSP = " + msp;
                listSP = new DAO().getListSanPham(sql);
                for (SanPham sp : listSP) {
                    slsql = sp.getMaSP();
                    gianhap = sp.getGiaNhap();
                }
                cthd.setMaCTHD(maCTHD);
                cthd.setMaHD(hd.getMaHD());
                new DAO().themchitiethoaDon(cthd, "INSERT INTO tblchitietnhaphang(machitietHD, maHD, maSP, tenSP, thanhtien) VALUES(?,?,?,?,?)");

                tongtien += gianhap;
                maCTHD++;
            }

            hd.setTongtien(tongtien);

            if (new DAO().themhoaDon(hd, "INSERT INTO tblnhaphang(maHD, ngaytao, tongtien) VALUES(?,?,?)")) {
                JOptionPane.showMessageDialog(rootPane, "Lưu thành công hóa đơn nhập hàng");
            } else {
                JOptionPane.showMessageDialog(rootPane, "Thất bại");
            }
        } 
        else if (rdXuatHang.isSelected()) {
            HoaDon hd = new HoaDon();
            String mahdcuoi = new DAO().getObject("SELECT MAX(maHD) FROM tblxuatkho").toString();
            hd.setMaHD(Integer.parseInt(mahdcuoi) + 1);
            hd.setNgaytaoHD(new java.sql.Date(System.currentTimeMillis()));

            float tongtien = 0;
            int maCTHD = 1;
            for (ChiTietHoaDon cthd : listNhapXuat) {
                int slsql = 0;
                float gianhap = 0;

                int msp = cthd.getMaSP();
                String sql = "SELECT * FROM tblsanpham WHERE maSP = " + msp;
                listSP = new DAO().getListSanPham(sql);
                for (SanPham sp : listSP) {
                    slsql = sp.getMaSP();
                    gianhap = sp.getGiaNhap();
                }
                cthd.setMaCTHD(maCTHD);
                cthd.setMaHD(hd.getMaHD());
                new DAO().themchitiethoaDon(cthd, "INSERT INTO tblchitietxuatkho(machitietHD, maHD, maSP, tenSP, thanhtien) VALUES(?,?,?,?,?)");

                tongtien += gianhap;
                maCTHD++;
            }

            hd.setTongtien(tongtien);

            if (new DAO().themhoaDon(hd, "INSERT INTO tblxuatkho(maHD, ngaytao, tongtien) VALUES(?,?,?)")) {
                JOptionPane.showMessageDialog(rootPane, "Lưu thành công hóa xuất kho");
            } else {
                JOptionPane.showMessageDialog(rootPane, "Thất bại");
            }
        }
    }//GEN-LAST:event_luuPhieu1ActionPerformed

    private void xoaPhieu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xoaPhieu1ActionPerformed
        listNhapXuat.remove(tblNhapXuat.getSelectedRow());
        showData(listNhapXuat, modelNhapXuat);
    }//GEN-LAST:event_xoaPhieu1ActionPerformed

    private void taoMoiHD1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_taoMoiHD1ActionPerformed
        listNhapXuat = new ArrayList<>();
        showData(listNhapXuat, modelNhapXuat);
        lbTongTien1.setText("0.0");
    }//GEN-LAST:event_taoMoiHD1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KhoHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KhoHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KhoHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KhoHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                KhoHang dialog = new KhoHang(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LamMoiSP1;
    private javax.swing.JButton capnhatSP1;
    private javax.swing.JComboBox<String> cbNhomSP1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lbTongTien1;
    private javax.swing.JLabel lbnhanvien;
    private javax.swing.JButton luuPhieu1;
    private javax.swing.JButton nhapMaSP1;
    private javax.swing.JRadioButton rdNhapHang;
    private javax.swing.JRadioButton rdXuatHang;
    private javax.swing.JButton taoMoiHD1;
    private javax.swing.JTable tblNhapXuat;
    private javax.swing.JTable tblSanPham1;
    private javax.swing.JTextField tfGiaBan1;
    private javax.swing.JTextField tfGiaNhap1;
    private javax.swing.JTextField tfMaSP1;
    private javax.swing.JTextField tfNHH1;
    private javax.swing.JTextField tfNSX1;
    private javax.swing.JTextField tfNhapSoLuong1;
    private javax.swing.JTextField tfTenSP1;
    private javax.swing.JButton timKiemSP1;
    private javax.swing.JButton xoaPhieu1;
    // End of variables declaration//GEN-END:variables

    @Override
    public <T> void showData(List<T> list, DefaultTableModel model) {
        model.setRowCount(0);
        int stt = 1;
        if (modelSP == model) {
            for (T t : list) {
                SanPham sp = (SanPham) t;
                model.addRow(new Object[]{
                    stt, sp.getMaSP(), sp.getTenSP(), sp.getNhomSP(), sp.getGiaNhap(), sp.getGiaBan(),
                    sp.getNgaySX(), sp.getHanSD()
                });
                stt++;
            }
        }
        if (modelSP1 == model) {
            for (T t : list) {
                SanPham sp = (SanPham) t;
                model.addRow(new Object[]{
                    stt, sp.getMaSP(), sp.getTenSP(), sp.getNhomSP()
                });
                stt++;
            }
        }
        if (modelNV == model) {
            for (T t : list) {
                NhanVien nv = (NhanVien) t;
                model.addRow(new Object[]{
                    stt, nv.getIdNv(), nv.getHoten(), nv.getDiachi(), nv.getNgaysinh(), nv.getSdt(),
                    nv.getTaikhoan(), nv.getMatkhau(), nv.getVitri()
                });
                stt++;
            }
        }
        if (modelSP2 == model) {
            for (T t : list) {
                SanPham sp = (SanPham) t;
                model.addRow(new Object[]{
                    stt, sp.getMaSP(), sp.getTenSP(), sp.getNhomSP()
                });
                stt++;
            }
        }
        if (modelNhapXuat == model) {
            for (T t : list) {
                ChiTietHoaDon cthd = (ChiTietHoaDon) t;
                model.addRow(new Object[]{
                    stt, cthd.getMaSP(), cthd.getTenSP(), cthd.getThanhtien()
                });
                stt++;
            }
        }
        if (modelBanHang == model) {
            for (T t : list) {
                ChiTietHoaDon cthd = (ChiTietHoaDon) t;
                model.addRow(new Object[]{
                    stt, cthd.getMaSP(), cthd.getTenSP(), cthd.getThanhtien()
                });
                stt++;
            }
        }
    }

    private void hienthiSP(int selectRow, String kt) {
        SanPham sp = new SanPham();
        ChiTietHoaDon cthd = new ChiTietHoaDon();
        if ("tabqlkho1".equals(kt)) {
            sp = listSP1.get(selectRow);

            String str1 = String.valueOf(sp.getNgaySX());
            String nsx = xulyngay(str1);
            String str2 = String.valueOf(sp.getHanSD());
            String hsd = xulyngay(str2);
            String str3 = String.valueOf(sp.getGiaNhap()).replace(".0", "");
            String str4 = String.valueOf(sp.getGiaBan()).replace(".0", "");

            tfMaSP1.setText(String.valueOf(sp.getMaSP()));
            tfTenSP1.setText(sp.getTenSP());
            cbNhomSP1.setSelectedItem(String.valueOf(sp.getNhomSP()));
            tfGiaNhap1.setText(str3);
            tfGiaBan1.setText(str4);
            tfNSX1.setText(nsx);
            tfNHH1.setText(hsd);

        } else if ("tabqlkho2".equals(kt)) {
            cthd = listNhapXuat.get(selectRow);
            String sql = "SELECT * FROM tblsanpham WHERE maSP = " + cthd.getMaSP();
            listSP = new DAO().getListSanPham(sql);
            sp = listSP.get(0);

            String str1 = String.valueOf(sp.getNgaySX());
            String nsx = xulyngay(str1);
            String str2 = String.valueOf(sp.getHanSD());
            String hsd = xulyngay(str2);
            String str3 = String.valueOf(sp.getGiaNhap()).replace(".0", "");
            String str4 = String.valueOf(sp.getGiaBan()).replace(".0", "");

            tfMaSP1.setText(String.valueOf(sp.getMaSP()));
            tfTenSP1.setText(sp.getTenSP());
            cbNhomSP1.setSelectedItem(String.valueOf(sp.getNhomSP()));
            tfGiaNhap1.setText(str3);
            tfGiaBan1.setText(str4);
            tfNSX1.setText(nsx);
            tfNHH1.setText(hsd);

        }
    }
}
